
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
    Congratulations on having your first pull request merged!
    The Iris community are stoked that you've contributed and we all look forward to
    your future work :smile: :tada: :fireworks:
