# (C) British Crown Copyright 2013, Met Office
#
# This file is part of Iris.
#
# Iris is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Iris is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Iris.  If not, see <http://www.gnu.org/licenses/>.

# DO NOT EDIT: AUTO-GENERATED 

import collections

CFname = collections.namedtuple('CFname', ['standard_name', 'long_name',
                                           'unit'])

LBFC_TO_CF = {	5 : CFname("atmosphere_boundary_layer_thickness", None, "m"),
	23 : CFname("soil_temperature", None, "K"),
	27 : CFname("air_density", None, "kg m-3"),
	36 : CFname("land_area_fraction", None, 1),
	37 : CFname("sea_ice_area_fraction", None, 1),
	50 : CFname("wind_speed", None, "m s-1"),
	73 : CFname("atmosphere_relative_vorticity", None, "s-1"),
	74 : CFname("divergence_of_wind", None, "s-1"),
	83 : CFname("potential_vorticity_of_atmosphere_layer", None, "Pa-1 s-1"),
	94 : CFname("convective_rainfall_amount", None, "kg m-2"),
	97 : CFname("rainfall_flux", None, "kg m-2 s-1"),
	102 : CFname("stratiform_rainfall_amount", None, "kg m-2"),
	108 : CFname("snowfall_flux", None, "kg m-2 s-1"),
	111 : CFname("surface_runoff_amount", None, "kg m-2"),
	116 : CFname("stratiform_snowfall_amount", None, "kg m-2"),
	117 : CFname("convective_snowfall_amount", None, "kg m-2"),
	122 : CFname("moisture_content_of_soil_layer", None, "kg m-2"),
	200 : CFname("toa_incoming_shortwave_flux", None, "W m-2"),
	203 : CFname("surface_downwelling_shortwave_flux_in_air", None, "W m-2"),
	206 : CFname("toa_outgoing_longwave_flux", None, "W m-2"),
	208 : CFname("surface_downwelling_shortwave_flux_in_air_assuming_clear_sky", None, "W m-2"),
	209 : CFname("sea_ice_temperature", None, "K"),
	253 : CFname("tendency_of_air_temperature_due_to_longwave_heating", None, "K s-1"),
	261 : CFname("downward_heat_flux_in_sea_ice", None, "W m-2"),
	321 : CFname("root_depth", None, "m"),
	326 : CFname("vegetation_area_fraction", None, 1),
	328 : CFname("surface_albedo_assuming_deep_snow", None, 1),
	329 : CFname("volume_fraction_of_condensed_water_in_soil_at_wilting_point", None, 1),
	330 : CFname("volume_fraction_of_condensed_water_in_soil_at_critical_point", None, 1),
	332 : CFname("soil_porosity", None, 1),
	333 : CFname("soil_hydraulic_conductivity_at_saturation", None, "m s-1"),
	335 : CFname("soil_thermal_capacity", None, "J kg-1 K-1"),
	336 : CFname("soil_thermal_conductivity", None, "W m-1 K-1"),
	342 : CFname("soil_suction_at_saturation", None, "Pa"),
	687 : CFname("sea_ice_thickness", None, "m"),
	701 : CFname("surface_eastward_sea_water_velocity", None, "m s-1"),
	702 : CFname("surface_northward_sea_water_velocity", None, "m s-1"),
	1025 : CFname("surface_downward_eastward_stress", None, "Pa"),
	1026 : CFname("surface_downward_northward_stress", None, "Pa"),
	1373 : CFname("mass_fraction_of_dimethyl_sulfide_in_air", None, 1),
	1374 : CFname("mass_fraction_of_sulfur_dioxide_in_air", None, 1),
	1382 : CFname("leaf_area_index", None, 1),
	1383 : CFname("canopy_height", None, "m"),
	1385 : CFname("mass_fraction_of_unfrozen_water_in_soil_moisture", None, 1),
	1386 : CFname("mass_fraction_of_frozen_water_in_soil_moisture", None, 1),
	1392 : CFname("leaf_area_index", None, 1),
	1393 : CFname("canopy_height", None, "m"),
	1395 : CFname("soil_albedo", None, 1),
	1507 : CFname("snow_grain_size", None, "1e-6 m"),
	1559 : CFname("soil_moisture_content_at_field_capacity", None, "kg m-2"),
	1720 : CFname("cloud_area_fraction_in_atmosphere_layer", None, 1),
	}

STASH_TO_CF = {
	"m01s00i001" : CFname("surface_air_pressure", None, "Pa"),
	"m01s00i002" : CFname("x_wind", None, "m s-1"),
	"m01s00i003" : CFname("y_wind", None, "m s-1"),
	"m01s00i004" : CFname("air_potential_temperature", None, "K"),
	"m01s00i009" : CFname("moisture_content_of_soil_layer", None, "kg m-2"),
	"m01s00i010" : CFname("specific_humidity", None, 1),
	"m01s00i012" : CFname("mass_fraction_of_cloud_ice_in_air", None, 1),
	"m01s00i013" : CFname("convective_cloud_area_fraction", None, 1),
	"m01s00i020" : CFname("soil_temperature", None, "K"),
	"m01s00i023" : CFname("snowfall_amount", None, "kg m-2"),
	"m01s00i024" : CFname("surface_temperature", None, "K"),
	"m01s00i025" : CFname("atmosphere_boundary_layer_thickness", None, "m"),
	"m01s00i026" : CFname("surface_roughness_length", None, "m"),
	"m01s00i028" : CFname("surface_eastward_sea_water_velocity", None, "m s-1"),
	"m01s00i029" : CFname("surface_northward_sea_water_velocity", None, "m s-1"),
	"m01s00i030" : CFname("land_binary_mask", None, 1),
	"m01s00i031" : CFname("sea_ice_area_fraction", None, 1),
	"m01s00i032" : CFname("sea_ice_thickness", None, "m"),
	"m01s00i033" : CFname("surface_altitude", None, "m"),
	"m01s00i040" : CFname("volume_fraction_of_condensed_water_in_soil_at_wilting_point", None, 1),
	"m01s00i041" : CFname("volume_fraction_of_condensed_water_in_soil_at_critical_point", None, 1),
	"m01s00i043" : CFname("soil_porosity", None, 1),
	"m01s00i044" : CFname("soil_hydraulic_conductivity_at_saturation", None, "m s-1"),
	"m01s00i046" : CFname("soil_thermal_capacity", None, "J kg-1 K-1"),
	"m01s00i047" : CFname("soil_thermal_conductivity", None, "W m-1 K-1"),
	"m01s00i048" : CFname("soil_suction_at_saturation", None, "Pa"),
	"m01s00i049" : CFname("sea_ice_temperature", None, "K"),
	"m01s00i050" : CFname("vegetation_area_fraction", None, 1),
	"m01s00i051" : CFname("root_depth", None, "m"),
	"m01s00i052" : CFname("surface_albedo_assuming_no_snow", None, 1),
	"m01s00i053" : CFname("surface_albedo_assuming_deep_snow", None, 1),
	"m01s00i060" : CFname("mass_fraction_of_ozone_in_air", None, 1),
	"m01s00i101" : CFname("mass_fraction_of_sulfur_dioxide_in_air", None, 1),
	"m01s00i102" : CFname("mass_fraction_of_dimethyl_sulfide_in_air", None, 1),
	"m01s00i150" : CFname("upward_air_velocity", None, "m s-1"),
	"m01s00i205" : CFname("land_area_fraction", None, 1),
	"m01s00i208" : CFname("leaf_area_index", None, 1),
	"m01s00i209" : CFname("canopy_height", None, "m"),
	"m01s00i214" : CFname("mass_fraction_of_unfrozen_water_in_soil_moisture", None, 1),
	"m01s00i215" : CFname("mass_fraction_of_frozen_water_in_soil_moisture", None, 1),
	"m01s00i217" : CFname("leaf_area_index", None, 1),
	"m01s00i218" : CFname("canopy_height", None, "m"),
	"m01s00i220" : CFname("soil_albedo", None, 1),
	"m01s00i223" : CFname("soil_carbon_content", None, "kg m-2"),
	"m01s00i231" : CFname("snow_grain_size", None, "1e-6 m"),
	"m01s00i252" : CFname("mass_fraction_of_carbon_dioxide_in_air", None, 1),
	"m01s00i254" : CFname("mass_fraction_of_cloud_liquid_water_in_air", None, 1),
	"m01s00i255" : CFname("dimensionless_exner_function", None, 1),
	"m01s00i269" : CFname("surface_eastward_sea_water_velocity", None, "m s-1"),
	"m01s00i270" : CFname("surface_northward_sea_water_velocity", None, "m s-1"),
	"m01s00i406" : CFname("dimensionless_exner_function", None, 1),
	"m01s00i407" : CFname("air_pressure", None, "Pa"),
	"m01s00i408" : CFname("air_pressure", None, "Pa"),
	"m01s00i409" : CFname("surface_air_pressure", None, "Pa"),
	"m01s00i505" : CFname("land_area_fraction", None, 1),
	"m01s00i506" : CFname("surface_temperature", None, "K"),
	"m01s00i507" : CFname("surface_temperature", None, "K"),
	"m01s00i508" : CFname("surface_temperature", None, "K"),
	"m01s00i509" : CFname("sea_ice_albedo", None, 1),
	"m01s01i004" : CFname("air_temperature", None, "K"),
	"m01s01i201" : CFname("surface_net_downward_shortwave_flux", None, "W m-2"),
	"m01s01i203" : CFname("surface_net_downward_shortwave_flux", None, "W m-2"),
	"m01s01i205" : CFname("toa_outgoing_shortwave_flux", None, "W m-2"),
	"m01s01i207" : CFname("toa_incoming_shortwave_flux", None, "W m-2"),
	"m01s01i208" : CFname("toa_outgoing_shortwave_flux", None, "W m-2"),
	"m01s01i209" : CFname("toa_outgoing_shortwave_flux_assuming_clear_sky", None, "W m-2"),
	"m01s01i210" : CFname("surface_downwelling_shortwave_flux_in_air_assuming_clear_sky", None, "W m-2"),
	"m01s01i211" : CFname("surface_upwelling_shortwave_flux_in_air_assuming_clear_sky", None, "W m-2"),
	"m01s01i232" : CFname("tendency_of_air_temperature_due_to_shortwave_heating", None, "unknown"),
	"m01s01i233" : CFname("tendency_of_air_temperature_due_to_shortwave_heating_assuming_clear_sky", None, "unknown"),
	"m01s01i235" : CFname("surface_downwelling_shortwave_flux_in_air", None, "W m-2"),
	"m01s01i237" : CFname("net_downward_shortwave_flux_in_air", None, "W m-2"),
	"m01s01i238" : CFname("tropopause_upwelling_shortwave_flux", None, "unknown"),
	"m01s01i410" : CFname("surface_downwelling_shortwave_flux_in_air_assuming_clear_sky", None, "W m-2"),
	"m01s01i435" : CFname("surface_downwelling_shortwave_flux_in_air", None, "W m-2"),
	"m01s02i004" : CFname("air_temperature", None, "K"),
	"m01s02i201" : CFname("surface_net_downward_longwave_flux", None, "W m-2"),
	"m01s02i203" : CFname("surface_net_downward_longwave_flux", None, "W m-2"),
	"m01s02i204" : CFname("cloud_area_fraction", None, 1),
	"m01s02i205" : CFname("toa_outgoing_longwave_flux", None, "W m-2"),
	"m01s02i206" : CFname("toa_outgoing_longwave_flux_assuming_clear_sky", None, "W m-2"),
	"m01s02i207" : CFname("surface_downwelling_longwave_flux_in_air", None, "W m-2"),
	"m01s02i208" : CFname("surface_downwelling_longwave_flux_in_air_assuming_clear_sky", None, "W m-2"),
	"m01s02i232" : CFname("tendency_of_air_temperature_due_to_longwave_heating", None, "K s-1"),
	"m01s02i233" : CFname("tendency_of_air_temperature_due_to_longwave_heating_assuming_clear_sky", None, "unknown"),
	"m01s02i237" : CFname("tropopause_net_downward_longwave_flux", None, "unknown"),
	"m01s02i238" : CFname("tropopause_downwelling_longwave_flux", None, "unknown"),
	"m01s02i260" : CFname("mass_fraction_of_ozone_in_air", None, 1),
	"m01s02i261" : CFname("cloud_area_fraction_in_atmosphere_layer", None, 1),
	"m01s03i004" : CFname("air_temperature", None, "m s-1"),
	"m01s03i010" : CFname("specific_humidity", None, 1),
	"m01s03i025" : CFname("atmosphere_boundary_layer_thickness", None, "m"),
	"m01s03i201" : CFname("downward_heat_flux_in_sea_ice", None, "W m-2"),
	"m01s03i202" : CFname("downward_heat_flux_in_soil", None, "unknown"),
	"m01s03i217" : CFname("surface_upward_sensible_heat_flux", None, "W m-2"),
	"m01s03i219" : CFname("surface_downward_eastward_stress", None, "Pa"),
	"m01s03i220" : CFname("surface_downward_northward_stress", None, "Pa"),
	"m01s03i223" : CFname("surface_upward_water_flux", None, "kg m-2 s-1"),
	"m01s03i224" : CFname("wind_mixing_energy_flux_into_sea_water", None, "W m-2"),
	"m01s03i225" : CFname("eastward_wind", None, "m s-1"),
	"m01s03i226" : CFname("northward_wind", None, "m s-1"),
	"m01s03i227" : CFname("wind_speed", None, "m s-1"),
	"m01s03i228" : CFname("surface_upward_sensible_heat_flux", None, "W m-2"),
	"m01s03i230" : CFname("wind_speed", None, "m s-1"),
	"m01s03i234" : CFname("surface_upward_latent_heat_flux", None, "W m-2"),
	"m01s03i236" : CFname("air_temperature", None, "K"),
	"m01s03i237" : CFname("specific_humidity", None, 1),
	"m01s03i238" : CFname("soil_temperature", None, "K"),
	"m01s03i245" : CFname("relative_humidity", None, "%"),
	"m01s03i249" : CFname("wind_speed", None, "m s-1"),
	"m01s03i258" : CFname("surface_snow_melt_heat_flux", None, "W m-2"),
	"m01s03i261" : CFname("gross_primary_productivity_of_carbon", None, "kg m-2 s-1"),
	"m01s03i262" : CFname("net_primary_productivity_of_carbon", None, "kg m-2 s-1"),
	"m01s03i295" : CFname(None, "surface_snow_area_fraction_where_land", "%"),
	"m01s03i298" : CFname("water_sublimation_flux", None, "kg m-2 s-1"),
	"m01s03i313" : CFname("soil_moisture_content_at_field_capacity", None, "kg m-2"),
	"m01s03i332" : CFname("toa_outgoing_longwave_flux", None, "W m-2"),
	"m01s03i334" : CFname("water_potential_evaporation_flux", None, "kg m-2 s-1"),
	"m01s03i337" : CFname("downward_heat_flux_in_soil", None, "W m-2"),
	"m01s03i391" : CFname("surface_downward_eastward_stress", None, "Pa"),
	"m01s03i392" : CFname("surface_downward_eastward_stress", None, "Pa"),
	"m01s03i393" : CFname("surface_downward_northward_stress", None, "Pa"),
	"m01s03i394" : CFname("surface_downward_northward_stress", None, "Pa"),
	"m01s03i460" : CFname("surface_downward_eastward_stress", None, "Pa"),
	"m01s03i461" : CFname("surface_downward_northward_stress", None, "Pa"),
	"m01s04i004" : CFname("air_temperature", None, "K"),
	"m01s04i010" : CFname("specific_humidity", None, 1),
	"m01s04i201" : CFname("stratiform_rainfall_amount", None, "kg m-2"),
	"m01s04i202" : CFname("stratiform_snowfall_amount", None, "kg m-2"),
	"m01s04i203" : CFname("stratiform_rainfall_rate", None, "kg m-2 s-1"),
	"m01s04i204" : CFname(None, "stratiform_snowfall_rate", "kg m-2 s-1"),
	"m01s05i010" : CFname("specific_humidity", None, 1),
	"m01s05i181" : CFname("tendency_of_air_temperature_due_to_convection", None, "K s-1"),
	"m01s05i182" : CFname("tendency_of_specific_humidity_due_to_convection", None, "s-1"),
	"m01s05i185" : CFname("tendency_of_eastward_wind_due_to_convection", None, "m s-2"),
	"m01s05i186" : CFname("tendency_of_northward_wind_due_to_convection", None, "m s-2"),
	"m01s05i201" : CFname("convective_rainfall_amount", None, "kg m-2"),
	"m01s05i202" : CFname("convective_snowfall_amount", None, "kg m-2"),
	"m01s05i205" : CFname("convective_rainfall_rate", None, "kg m-2 s-1"),
	"m01s05i206" : CFname("convective_snowfall_flux", None, "kg m-2 s-1"),
	"m01s05i209" : CFname("air_temperature", None, "K"),
	"m01s05i212" : CFname("convective_cloud_area_fraction_in_atmosphere_layer", None, "unknown"),
	"m01s05i213" : CFname("mass_fraction_of_convective_cloud_liquid_water_in_air", None, 1),
	"m01s05i214" : CFname("rainfall_flux", None, "kg m-2 s-1"),
	"m01s05i215" : CFname("snowfall_flux", None, "kg m-2 s-1"),
	"m01s05i216" : CFname("precipitation_flux", None, "kg m-2 s-1"),
	"m01s05i233" : CFname("mass_fraction_of_convective_cloud_liquid_water_in_air", None, 1),
	"m01s06i185" : CFname("tendency_of_eastward_wind_due_to_gravity_wave_drag", None, "m s-2"),
	"m01s06i186" : CFname("tendency_of_northward_wind_due_to_gravity_wave_drag", None, "m s-2"),
	"m01s06i201" : CFname("atmosphere_eastward_stress_due_to_gravity_wave_drag", None, "Pa"),
	"m01s06i202" : CFname("atmosphere_northward_stress_due_to_gravity_wave_drag", None, "Pa"),
	"m01s08i023" : CFname("surface_snow_amount", None, "kg m-2"),
	"m01s08i202" : CFname(None, "surface_snow_melt_flux_where_land", "kg m-2 s-1"),
	"m01s08i204" : CFname("surface_runoff_amount", None, "kg m-2"),
	"m01s08i205" : CFname("subsurface_runoff_amount", None, "kg m-2"),
	"m01s08i208" : CFname("soil_moisture_content", None, "unknown"),
	"m01s08i209" : CFname("canopy_water_amount", None, "unknown"),
	"m01s08i223" : CFname("moisture_content_of_soil_layer", None, "kg m-2"),
	"m01s08i225" : CFname("soil_temperature", None, "K"),
	"m01s08i229" : CFname("mass_fraction_of_unfrozen_water_in_soil_moisture", None, "unknown"),
	"m01s08i230" : CFname("mass_fraction_of_frozen_water_in_soil_moisture", None, "unknown"),
	"m01s08i231" : CFname(None, "surface_snow_melt_flux_where_land", "kg m-2 s-1"),
	"m01s08i234" : CFname("surface_runoff_flux", None, "kg m-2 s-1"),
	"m01s08i235" : CFname("subsurface_runoff_flux", None, "kg m-2 s-1"),
	"m01s09i004" : CFname("air_temperature", None, "K"),
	"m01s09i010" : CFname("specific_humidity", None, 1),
	"m01s09i201" : CFname("stratiform_cloud_area_fraction_in_atmosphere_layer", None, 1),
	"m01s12i004" : CFname("air_temperature", None, "K"),
	"m01s12i010" : CFname("specific_humidity", None, 1),
	"m01s12i012" : CFname("mass_fraction_of_cloud_ice_in_air", None, 1),
	"m01s12i181" : CFname("tendency_of_air_temperature_due_to_advection", None, "K s-1"),
	"m01s12i182" : CFname("tendency_of_specific_humidity_due_to_advection", None, "s-1"),
	"m01s12i183" : CFname("tendency_of_mass_fraction_of_cloud_liquid_water_in_air_due_to_advection", None, "s-1"),
	"m01s12i184" : CFname("tendency_of_mass_fraction_of_cloud_ice_in_air_due_to_advection", None, "s-1"),
	"m01s12i185" : CFname("tendency_of_eastward_wind_due_to_advection", None, "m s-1"),
	"m01s12i186" : CFname("tendency_of_northward_wind_due_to_advection", None, "m s-1"),
	"m01s12i187" : CFname("tendency_of_upward_air_velocity_due_to_advection", None, "m s-1"),
	"m01s12i201" : CFname("lagrangian_tendency_of_air_pressure", None, "Pa s-1"),
	"m01s13i181" : CFname("tendency_of_air_temperature_due_to_diffusion", None, "K s-1"),
	"m01s13i182" : CFname("tendency_of_specific_humidity_due_to_diffusion", None, "s-1"),
	"m01s13i185" : CFname("tendency_of_eastward_wind_due_to_diffusion", None, "m s-1"),
	"m01s13i186" : CFname("tendency_of_northward_wind_due_to_diffusion", None, "m s-1"),
	"m01s15i108" : CFname("air_pressure", None, "Pa"),
	"m01s15i119" : CFname("air_potential_temperature", None, "K"),
	"m01s15i127" : CFname("air_density", None, "kg m-3"),
	"m01s15i142" : CFname("upward_air_velocity", None, "m s-1"),
	"m01s15i143" : CFname("eastward_wind", None, "m s-1"),
	"m01s15i144" : CFname("northward_wind", None, "m s-1"),
	"m01s15i201" : CFname("eastward_wind", None, "m s-1"),
	"m01s15i202" : CFname("northward_wind", None, "m s-1"),
	"m01s15i214" : CFname("ertel_potential_vorticity", None, "K m2 kg-1 s-1"),
	"m01s15i215" : CFname("air_potential_temperature", None, "K"),
	"m01s15i216" : CFname("air_potential_temperature", None, "K"),
	"m01s15i217" : CFname("potential_vorticity_of_atmosphere_layer", None, "Pa-1 s-1"),
	"m01s15i218" : CFname("potential_vorticity_of_atmosphere_layer", None, "Pa-1 s-1"),
	"m01s15i219" : CFname("square_of_air_temperature", None, "unknown"),
	"m01s15i220" : CFname("square_of_eastward_wind", None, "unknown"),
	"m01s15i221" : CFname("square_of_northward_wind", None, "unknown"),
	"m01s15i222" : CFname("lagrangian_tendency_of_air_pressure", None, "Pa s-1"),
	"m01s15i223" : CFname("product_of_omega_and_air_temperature", None, "unknown"),
	"m01s15i224" : CFname("product_of_eastward_wind_and_omega", None, "unknown"),
	"m01s15i225" : CFname("product_of_northward_wind_and_omega", None, "unknown"),
	"m01s15i226" : CFname("specific_humidity", None, "unknown"),
	"m01s15i227" : CFname("product_of_eastward_wind_and_specific_humidity", None, "unknown"),
	"m01s15i228" : CFname("product_of_northward_wind_and_specific_humidity", None, "unknown"),
	"m01s15i235" : CFname("product_of_omega_and_specific_humidity", None, "unknown"),
	"m01s15i238" : CFname("geopotential_height", None, "unknown"),
	"m01s15i239" : CFname("product_of_eastward_wind_and_geopotential_height", None, "unknown"),
	"m01s15i240" : CFname("product_of_northward_wind_and_geopotential_height", None, "unknown"),
	"m01s15i242" : CFname("upward_air_velocity", None, "m s-1"),
	"m01s15i243" : CFname("eastward_wind", None, "m s-1"),
	"m01s15i244" : CFname("northward_wind", None, "m s-1"),
	"m01s16i004" : CFname("air_temperature", None, "K"),
	"m01s16i201" : CFname("geopotential_height", None, "m"),
	"m01s16i202" : CFname("geopotential_height", None, "m"),
	"m01s16i203" : CFname("air_temperature", None, "K"),
	"m01s16i204" : CFname("relative_humidity", None, "%"),
	"m01s16i222" : CFname("air_pressure_at_sea_level", None, "Pa"),
	"m01s16i224" : CFname(None, "square_of_height", "m2"),
	"m01s16i255" : CFname("geopotential_height", None, "m"),
	"m01s20i003" : CFname("wind_speed", None, "m s-1"),
	"m01s20i004" : CFname("wind_speed", None, "m s-1"),
	"m01s20i005" : CFname("divergence_of_wind", None, "s-1"),
	"m01s20i006" : CFname("atmosphere_relative_vorticity", None, "s-1"),
	"m01s20i024" : CFname("tropopause_air_pressure", None, "Pa"),
	"m01s20i025" : CFname("tropopause_air_temperature", None, "K"),
	"m01s20i026" : CFname("tropopause_altitude", None, "m"),
	"m01s20i034" : CFname("air_pressure_at_freezing_level", None, "Pa"),
	"m01s20i064" : CFname("tropopause_air_pressure", None, "Pa"),
	"m01s20i065" : CFname("tropopause_air_temperature", None, "K"),
	"m01s20i066" : CFname("tropopause_altitude", None, "m"),
	"m01s30i003" : CFname("upward_air_velocity", None, "m s-1"),
	"m01s30i004" : CFname("air_temperature", None, "K"),
	"m01s30i005" : CFname("specific_humidity", None, 1),
	"m01s30i007" : CFname("specific_kinetic_energy_of_air", None, "m2 s-2"),
	"m01s30i111" : CFname("air_temperature", None, "K"),
	"m01s30i113" : CFname("relative_humidity", None, "%"),
	"m01s30i181" : CFname("tendency_of_air_temperature", None, "K s-1"),
	"m01s30i182" : CFname("tendency_of_specific_humidity", None, "s-1"),
	"m01s30i183" : CFname("tendency_of_mass_fraction_of_cloud_liquid_water_in_air", None, "s-1"),
	"m01s30i184" : CFname("tendency_of_mass_fraction_of_cloud_ice_in_air", None, "s-1"),
	"m01s30i185" : CFname("tendency_of_eastward_wind", None, "m s-1"),
	"m01s30i186" : CFname("tendency_of_northward_wind", None, "m s-1"),
	"m01s30i187" : CFname("tendency_of_upward_air_velocity", None, "m s-1"),
	"m01s30i188" : CFname("tendency_of_air_density", None, "kg m-3 s-1"),
	"m01s30i201" : CFname("eastward_wind", None, "m s-1"),
	"m01s30i202" : CFname("northward_wind", None, "m s-1"),
	"m01s30i203" : CFname("upward_air_velocity", None, "m s-1"),
	"m01s30i204" : CFname("air_temperature", None, "K"),
	"m01s30i205" : CFname("specific_humidity", None, 1),
	"m01s30i207" : CFname("geopotential_height", None, "m"),
	"m01s30i208" : CFname("lagrangian_tendency_of_air_pressure", None, "Pa s-1"),
	"m01s30i211" : CFname("square_of_eastward_wind", None, "m2 s-2"),
	"m01s30i212" : CFname("product_of_eastward_wind_and_northward_wind", None, "m2 s-2"),
	"m01s30i213" : CFname("product_of_eastward_wind_and_upward_air_velocity", None, "m2 s-2"),
	"m01s30i214" : CFname("product_of_eastward_wind_and_air_temperature", None, "K m s-1"),
	"m01s30i215" : CFname("product_of_eastward_wind_and_specific_humidity", None, "m s-1"),
	"m01s30i217" : CFname("product_of_eastward_wind_and_geopotential_height", None, "m2 s-1"),
	"m01s30i218" : CFname("product_of_eastward_wind_and_omega", None, "Pa m s-1"),
	"m01s30i222" : CFname("square_of_northward_wind", None, "m2 s-2"),
	"m01s30i223" : CFname("product_of_northward_wind_and_upward_air_velocity", None, "m2 s-2"),
	"m01s30i224" : CFname("product_of_northward_wind_and_air_temperature", None, "K m s-1"),
	"m01s30i225" : CFname("product_of_northward_wind_and_specific_humidity", None, "m s-1"),
	"m01s30i227" : CFname("product_of_northward_wind_and_geopotential_height", None, "m2 s-1"),
	"m01s30i228" : CFname("product_of_northward_wind_and_omega", None, "Pa m s-1"),
	"m01s30i233" : CFname("square_of_upward_air_velocity", None, "m2 s-2"),
	"m01s30i234" : CFname("product_of_upward_air_velocity_and_air_temperature", None, "K m s-1"),
	"m01s30i235" : CFname("product_of_upward_air_velocity_and_specific_humidity", None, "m s-1"),
	"m01s30i244" : CFname("square_of_air_temperature", None, "K2"),
	"m01s30i245" : CFname("product_of_air_temperature_and_specific_humidity", None, "K"),
	"m01s30i248" : CFname("product_of_air_temperature_and_omega", None, "K Pa s-1"),
	"m01s30i258" : CFname("product_of_specific_humidity_and_omega", None, "Pa s-1"),
	"m01s30i277" : CFname("square_of_geopotential_height", None, "m2"),
	"m01s30i278" : CFname("product_of_geopotential_height_and_omega", None, "Pa m s-1"),
	"m01s30i288" : CFname("square_of_lagrangian_tendency_of_air_pressure", None, "Pa2 s-2"),
	"m01s30i302" : CFname("virtual_temperature", None, "K"),
	"m01s30i310" : CFname("northward_transformed_eulerian_mean_air_velocity", None, "MKS"),
	"m01s30i311" : CFname("northward_transformed_eulerian_mean_air_velocity", None, "MKS"),
	"m01s30i312" : CFname("northward_eliassen_palm_flux_in_air", None, "MKS"),
	"m01s30i313" : CFname("upward_eliassen_palm_flux_in_air", None, "MKS"),
	"m01s30i314" : CFname("tendency_of_eastward_wind_due_to_eliassen_palm_flux_divergence", None, "MKS"),
	"m01s30i401" : CFname("atmosphere_kinetic_energy_content", None, "J m-2"),
	"m01s30i405" : CFname("atmosphere_cloud_liquid_water_content", None, "kg m-2"),
	"m01s30i406" : CFname("atmosphere_cloud_ice_content", None, "kg m-2"),
	"m01s30i417" : CFname("surface_air_pressure", None, "Pa"),
	"m01s30i418" : CFname("surface_air_pressure", None, "Pa"),
	"m01s30i451" : CFname("tropopause_air_pressure", None, "Pa"),
	"m01s30i452" : CFname("tropopause_air_temperature", None, "K"),
	"m01s30i453" : CFname("tropopause_altitude", None, "m"),
	"m01s33i001" : CFname("mole_fraction_of_ozone_in_air", None, "mole mole-1"),
	"m01s33i004" : CFname(None, "mole_fraction_of_nitrogen_trioxide_in_air", "mole mole-1"),
	"m01s33i005" : CFname("mole_fraction_of_dinitrogen_pentoxide_in_air", None, "mole mole-1"),
	"m01s33i006" : CFname("mole_fraction_of_peroxynitric_acid_in_air", None, "mole mole-1"),
	"m01s33i007" : CFname("mole_fraction_of_chlorine_nitrate_in_air", None, "mole mole-1"),
	"m01s33i009" : CFname("mole_fraction_of_methane_in_air", None, "mole mole-1"),
	"m01s33i041" : CFname("mole_fraction_of_atomic_chlorine_in_air", None, 1),
	"m01s33i042" : CFname("mole_fraction_of_chlorine_monoxide_in_air", None, 1),
	"m01s33i043" : CFname("mole_fraction_of_dichlorine_peroxide_in_air", None, 1),
	"m01s33i044" : CFname("mole_fraction_of_chlorine_dioxide_in_air", None, 1),
	"m01s33i047" : CFname("mole_fraction_of_bromine_chloride_in_air", None, 1),
	"m01s33i048" : CFname("mole_fraction_of_bromine_nitrate_in_air", None, 1),
	"m01s33i049" : CFname("mole_fraction_of_nitrous_oxide_in_air", None, 1),
	"m01s33i051" : CFname("mole_fraction_of_hypochlorous_acid_in_air", None, 1),
	"m01s33i054" : CFname("mole_fraction_of_chlorine_nitrate_in_air", None, 1),
	"m01s33i055" : CFname("mole_fraction_of_cfc11_in_air", None, 1),
	"m01s33i056" : CFname("mole_fraction_of_cfc12_in_air", None, 1),
	"m01s33i058" : CFname("mole_fraction_of_atomic_nitrogen_in_air", None, 1),
	"m01s33i150" : CFname("age_of_stratospheric_air", None, 1),
	"m01s34i001" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i002" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i003" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i004" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i005" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i006" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i007" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i008" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i009" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i010" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i011" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i012" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i013" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i014" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i015" : CFname(None, "mass_fraction_of_ethyl_hydroperoxide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i016" : CFname(None, "mass_fraction_of_acetaldehyde_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i017" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i018" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i019" : CFname(None, "mass_fraction_of_n-propyl_hydroperoxide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i020" : CFname(None, "mass_fraction_of_i-propyl_hydroperoxide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i021" : CFname(None, "mass_fraction_of_propanal_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i022" : CFname(None, "mass_fraction_of_acetone_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i023" : CFname(None, "mass_fraction_of_acetonylhydroperoxide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i024" : CFname(None, "mass_fraction_of_peroxypropionyl_nitrate_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i025" : CFname(None, "mass_fraction_of_methyl_nitrate_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i026" : CFname(None, "mass_fraction_of_stratospheric_ozone_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i027" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i028" : CFname(None, "mass_fraction_of_isoprene_hydroperoxide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i030" : CFname(None, "mass_fraction_of_methacrolein_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i031" : CFname(None, "mass_fraction_of_methacroyl_hydroperoxide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i032" : CFname(None, "mass_fraction_of_methacryloylperoxy_nitrate_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i033" : CFname(None, "mass_fraction_of_hydroxyacetone_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i034" : CFname(None, "mass_fraction_of_methlyglyoxal_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i035" : CFname(None, "mass_fraction_of_second_generation_isoprene_nitrate_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i036" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i037" : CFname(None, "mass_fraction_of_peracetic_acid_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i038" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i041" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i042" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i043" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i044" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i045" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i047" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i048" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i049" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i051" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i052" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i053" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i054" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i055" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i056" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i057" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i058" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i059" : CFname(None, "mass_fraction_of_ground_state_atomic_oxygen_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i070" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i071" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i072" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i073" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i074" : CFname(None, "mass_fraction_of_methanesulfonic_acid_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i075" : CFname(None, "mass_fraction_of_dimethyl_sulfoxide", "Mass mixing ratio (kg/kg)"),
	"m01s34i076" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i077" : CFname(None, "mass_fraction_of_carbon_disulfide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i078" : CFname(None, "mass_fraction_of_carbonyl_sulfide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i079" : CFname(None, "mass_fraction_of_hydrogen_sulfide_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i080" : CFname(None, "mass_fraction_of_atomic_hydrogen_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i081" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i082" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i083" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i084" : CFname(None, "mass_fraction_of_ethyl_peroxy_radical_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i085" : CFname(None, "mass_fraction_of_peroxyacetyl_radical_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i086" : CFname(None, "mass_fraction_of_n-propylperoxy_radical_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i087" : CFname(None, "mass_fraction_of_isopropylperoxy_radical_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i088" : CFname(None, "mass_fraction_of_peroxypropanoyl_radical_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i089" : CFname(None, "mass_fraction_of_acetonyl_peroxy_radical_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i093" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i096" : CFname(None, "mass_fraction_of_methyl_ethyl_ketone_in_air", "Mass mixing ratio (kg/kg)"),
	"m01s34i097" : CFname(None, None, "Mass mixing ratio (kg/kg)"),
	"m01s34i100" : CFname(None, "mass_fraction_of_lumped_chlorine_expressed_as_hydrogen_chloride", "Mass mixing ratio (kg/kg)"),
	"m02s00i101" : CFname("sea_water_potential_temperature", None, "degC"),
	"m02s00i102" : CFname("sea_water_salinity", None, "1e3 psu @0.035"),
	"m02s00i121" : CFname("baroclinic_eastward_sea_water_velocity", None, "cm s-1"),
	"m02s00i122" : CFname("baroclinic_northward_sea_water_velocity", None, "cm s-1"),
	"m02s00i130" : CFname("ocean_barotropic_streamfunction", None, "cm3 s-1"),
	"m02s00i131" : CFname("ocean_barotropic_streamfunction", None, "cm3 s-1"),
	"m02s00i132" : CFname("tendency_of_ocean_barotropic_streamfunction", None, "cm3 s-2"),
	"m02s00i133" : CFname("tendency_of_ocean_barotropic_streamfunction", None, "cm3 s-2"),
	"m02s00i134" : CFname("surface_air_pressure", None, "g cm-1 s-2"),
	"m02s00i135" : CFname("barotropic_eastward_sea_water_velocity", None, "cm s-1"),
	"m02s00i136" : CFname("barotropic_northward_sea_water_velocity", None, "cm s-1"),
	"m02s00i137" : CFname("ocean_mixed_layer_thickness", None, "m"),
	"m02s00i139" : CFname("downward_eastward_stress_at_sea_ice_base", None, "Pa"),
	"m02s00i140" : CFname("downward_northward_stress_at_sea_ice_base", None, "Pa"),
	"m02s00i141" : CFname("surface_snow_thickness", None, "m"),
	"m02s00i143" : CFname("upward_sea_ice_basal_heat_flux", None, "W m-2"),
	"m02s00i146" : CFname("sea_ice_area_fraction", None, 1),
	"m02s00i147" : CFname("sea_ice_thickness", None, "m"),
	"m02s00i148" : CFname("eastward_sea_ice_velocity", None, "m s-1"),
	"m02s00i149" : CFname("northward_sea_ice_velocity", None, "m s-1"),
	"m02s00i150" : CFname("surface_downward_eastward_stress", None, "Pa"),
	"m02s00i151" : CFname("surface_downward_northward_stress", None, "Pa"),
	"m02s00i152" : CFname("wind_mixing_energy_flux_into_sea_water", None, "W m-2"),
	"m02s00i166" : CFname("water_flux_into_sea_water_from_rivers", None, "kg m-2 s-1"),
	"m02s00i171" : CFname("snowfall_flux", None, "kg m-2 s-1"),
	"m02s00i180" : CFname("sea_surface_temperature", None, "K"),
	"m02s00i181" : CFname("sea_surface_salinity", None, "1e3 psu @0.035"),
	"m02s00i182" : CFname("air_temperature", None, "K"),
	"m02s00i183" : CFname("sea_ice_thickness", None, "m"),
	"m02s00i185" : CFname("heat_flux_correction", None, "W m-2"),
	"m02s00i186" : CFname("water_flux_correction", None, "Kg m-2 s-1"),
	"m02s00i190" : CFname("surface_snow_and_ice_melt_heat_flux", None, "W m-2"),
	"m02s00i191" : CFname("downward_heat_flux_in_sea_ice", None, "W m-2"),
	"m02s30i201" : CFname("upward_sea_water_velocity", None, "cm s-1"),
	"m02s30i202" : CFname("ocean_mixed_layer_thickness", None, "m"),
	"m02s30i211" : CFname("northward_ocean_heat_transport", None, "PW"),
	"m02s30i212" : CFname("northward_ocean_salt_transport", None, "1e7kg s-1"),
	"m02s30i320" : CFname("eastward_sea_water_velocity", None, "cm s-1"),
	"m02s30i321" : CFname("northward_sea_water_velocity", None, "cm s-1"),
	"m02s30i324" : CFname("ocean_mixed_layer_thickness", None, "m"),
	"m02s32i201" : CFname("tendency_of_sea_ice_area_fraction_due_to_dynamics", None, "s-1"),
	"m02s32i202" : CFname("tendency_of_sea_ice_thickness_due_to_dynamics", None, "m s-1"),
	"m02s32i209" : CFname("eastward_sea_ice_velocity", None, "m s-1"),
	"m02s32i210" : CFname("northward_sea_ice_velocity", None, "m s-1"),
	"m02s32i211" : CFname("tendency_of_sea_ice_area_fraction_due_to_thermodynamics", None, "s-1"),
	"m02s32i212" : CFname("tendency_of_sea_ice_thickness_due_to_thermodynamics", None, "m s-1"),
	"m02s32i219" : CFname("downward_eastward_stress_at_sea_ice_base", None, "Pa"),
	"m02s32i220" : CFname("downward_northward_stress_at_sea_ice_base", None, "Pa"),
	"m03s00i177" : CFname(None, "prescribed_heat_flux_into_slab_ocean", "W m-2"),
	}

CF_TO_LBFC = {
	CFname("age_of_stratospheric_air", None, 1) : 501,
	CFname("air_density", None, "kg m-3") : 27,
	CFname("air_potential_temperature", None, "K") : 19,
	CFname("air_pressure", None, "Pa") : 8,
	CFname("air_pressure_at_freezing_level", None, "Pa") : 8,
	CFname("air_pressure_at_sea_level", None, "Pa") : 8,
	CFname("atmosphere_boundary_layer_thickness", None, "m") : 5,
	CFname("atmosphere_eastward_stress_due_to_gravity_wave_drag", None, "Pa") : 61,
	CFname("atmosphere_kinetic_energy_content", None, "J m-2") : 63,
	CFname("atmosphere_northward_stress_due_to_gravity_wave_drag", None, "Pa") : 62,
	CFname("atmosphere_relative_vorticity", None, "s-1") : 73,
	CFname("cloud_area_fraction", None, 1) : 30,
	CFname("cloud_area_fraction_in_atmosphere_layer", None, 1) : 1720,
	CFname("convective_cloud_area_fraction", None, 1) : 34,
	CFname("convective_rainfall_amount", None, "kg m-2") : 94,
	CFname("convective_snowfall_amount", None, "kg m-2") : 117,
	CFname("dimensionless_exner_function", None, 1) : 7,
	CFname("divergence_of_wind", None, "s-1") : 74,
	CFname("downward_heat_flux_in_sea_ice", None, "W m-2") : 261,
	CFname("downward_heat_flux_in_soil", None, "W m-2") : 1564,
	CFname("ertel_potential_vorticity", None, "K m2 kg-1 s-1") : 82,
	CFname("geopotential_height", None, "m") : 1,
	CFname("lagrangian_tendency_of_air_pressure", None, "Pa s-1") : 40,
	CFname("land_binary_mask", None, 1) : 395,
	CFname("mass_fraction_of_carbon_dioxide_in_air", None, 1) : 1564,
	CFname("mass_fraction_of_cloud_liquid_water_in_air", None, 1) : 79,
	CFname("mass_fraction_of_dimethyl_sulfide_in_air", None, 1) : 1373,
	CFname("mass_fraction_of_frozen_water_in_soil_moisture", None, 1) : 1386,
	CFname("mass_fraction_of_ozone_in_air", None, 1) : 453,
	CFname("mass_fraction_of_sulfur_dioxide_in_air", None, 1) : 1374,
	CFname("mass_fraction_of_unfrozen_water_in_soil_moisture", None, 1) : 1385,
	CFname("moisture_content_of_soil_layer", None, "kg m-2") : 122,
	CFname("mole_fraction_of_atomic_chlorine_in_air", None, 1) : 501,
	CFname("mole_fraction_of_atomic_nitrogen_in_air", None, 1) : 501,
	CFname("mole_fraction_of_bromine_chloride_in_air", None, 1) : 501,
	CFname("mole_fraction_of_bromine_nitrate_in_air", None, 1) : 501,
	CFname("mole_fraction_of_cfc11_in_air", None, 1) : 501,
	CFname("mole_fraction_of_cfc12_in_air", None, 1) : 501,
	CFname("mole_fraction_of_chlorine_dioxide_in_air", None, 1) : 501,
	CFname("mole_fraction_of_chlorine_monoxide_in_air", None, 1) : 501,
	CFname("mole_fraction_of_chlorine_nitrate_in_air", None, 1) : 501,
	CFname("mole_fraction_of_dichlorine_peroxide_in_air", None, 1) : 501,
	CFname("mole_fraction_of_hypochlorous_acid_in_air", None, 1) : 501,
	CFname("mole_fraction_of_nitrous_oxide_in_air", None, 1) : 501,
	CFname("rainfall_flux", None, "kg m-2 s-1") : 97,
	CFname("relative_humidity", None, "%") : 88,
	CFname("root_depth", None, "m") : 321,
	CFname("sea_ice_albedo", None, 1) : 322,
	CFname("sea_ice_area_fraction", None, 1) : 37,
	CFname("sea_ice_temperature", None, "K") : 209,
	CFname("sea_ice_thickness", None, "m") : 687,
	CFname("snow_grain_size", None, "1e-6 m") : 1507,
	CFname("snowfall_amount", None, "kg m-2") : 93,
	CFname("snowfall_flux", None, "kg m-2 s-1") : 108,
	CFname("soil_albedo", None, 1) : 1395,
	CFname("soil_carbon_content", None, "kg m-2") : 1397,
	CFname("soil_hydraulic_conductivity_at_saturation", None, "m s-1") : 333,
	CFname("soil_moisture_content_at_field_capacity", None, "kg m-2") : 1559,
	CFname("soil_porosity", None, 1) : 332,
	CFname("soil_suction_at_saturation", None, "Pa") : 342,
	CFname("soil_temperature", None, "K") : 23,
	CFname("soil_thermal_capacity", None, "J kg-1 K-1") : 335,
	CFname("soil_thermal_conductivity", None, "W m-1 K-1") : 336,
	CFname("specific_kinetic_energy_of_air", None, "m2 s-2") : 60,
	CFname("stratiform_cloud_area_fraction_in_atmosphere_layer", None, 1) : 220,
	CFname("stratiform_rainfall_amount", None, "kg m-2") : 102,
	CFname("stratiform_rainfall_rate", None, "kg m-2 s-1") : 99,
	CFname("stratiform_snowfall_amount", None, "kg m-2") : 116,
	CFname("subsurface_runoff_amount", None, "kg m-2") : 112,
	CFname("subsurface_runoff_flux", None, "kg m-2 s-1") : 1533,
	CFname("surface_albedo_assuming_deep_snow", None, 1) : 328,
	CFname("surface_albedo_assuming_no_snow", None, 1) : 322,
	CFname("surface_altitude", None, "m") : 1,
	CFname("surface_downwelling_shortwave_flux_in_air", None, "W m-2") : 203,
	CFname("surface_downwelling_shortwave_flux_in_air_assuming_clear_sky", None, "W m-2") : 208,
	CFname("surface_eastward_sea_water_velocity", None, "m s-1") : 701,
	CFname("surface_net_downward_longwave_flux", None, "W m-2") : 187,
	CFname("surface_net_downward_shortwave_flux", None, "W m-2") : 186,
	CFname("surface_northward_sea_water_velocity", None, "m s-1") : 702,
	CFname("surface_roughness_length", None, "m") : 324,
	CFname("surface_runoff_amount", None, "kg m-2") : 111,
	CFname("surface_runoff_flux", None, "kg m-2 s-1") : 1532,
	CFname("surface_snow_amount", None, "kg m-2") : 93,
	CFname("surface_temperature", None, "K") : 16,
	CFname("surface_upward_sensible_heat_flux", None, "W m-2") : 178,
	CFname("surface_upward_water_flux", None, "kg m-2 s-1") : 184,
	CFname("surface_upwelling_shortwave_flux_in_air_assuming_clear_sky", None, "W m-2") : 207,
	CFname("tendency_of_air_density", None, "kg m-3 s-1") : 7,
	CFname("tendency_of_air_temperature", None, "K s-1") : 16,
	CFname("tendency_of_air_temperature_due_to_diffusion", None, "K s-1") : 16,
	CFname("tendency_of_air_temperature_due_to_longwave_heating", None, "K s-1") : 253,
	CFname("tendency_of_eastward_wind", None, "m s-1") : 56,
	CFname("tendency_of_eastward_wind_due_to_diffusion", None, "m s-1") : 56,
	CFname("tendency_of_mass_fraction_of_cloud_ice_in_air", None, "s-1") : 78,
	CFname("tendency_of_mass_fraction_of_cloud_liquid_water_in_air", None, "s-1") : 79,
	CFname("tendency_of_northward_wind", None, "m s-1") : 57,
	CFname("tendency_of_northward_wind_due_to_diffusion", None, "m s-1") : 57,
	CFname("tendency_of_specific_humidity", None, "s-1") : 95,
	CFname("tendency_of_specific_humidity_due_to_diffusion", None, "s-1") : 95,
	CFname("tendency_of_upward_air_velocity", None, "m s-1") : 42,
	CFname("toa_incoming_shortwave_flux", None, "W m-2") : 200,
	CFname("toa_outgoing_longwave_flux", None, "W m-2") : 206,
	CFname("toa_outgoing_longwave_flux_assuming_clear_sky", None, "W m-2") : 210,
	CFname("toa_outgoing_shortwave_flux", None, "W m-2") : 201,
	CFname("toa_outgoing_shortwave_flux_assuming_clear_sky", None, "W m-2") : 207,
	CFname("tropopause_air_pressure", None, "Pa") : 8,
	CFname("tropopause_air_temperature", None, "K") : 16,
	CFname("tropopause_altitude", None, "m") : 1,
	CFname("upward_air_velocity", None, "m s-1") : 42,
	CFname("vegetation_area_fraction", None, 1) : 326,
	CFname("virtual_temperature", None, "K") : 16,
	CFname("volume_fraction_of_condensed_water_in_soil_at_critical_point", None, 1) : 330,
	CFname("volume_fraction_of_condensed_water_in_soil_at_wilting_point", None, 1) : 329,
	CFname("water_potential_evaporation_flux", None, "kg m-2 s-1") : 115,
	CFname("wind_mixing_energy_flux_into_sea_water", None, "W m-2") : 182,
	CFname(None, "stratiform_snowfall_rate", "kg m-2 s-1") : 118,
	}
