.. _SciTools: https://github.com/SciTools
.. _Iris: https://github.com/SciTools/iris
.. _Iris GitHub: https://github.com/SciTools/iris
.. _iris mailing list: https://groups.google.com/forum/#!forum/scitools-iris
.. _issue: https://github.com/SciTools/iris/issues
.. _issues: https://github.com/SciTools/iris/issues
.. _pull request: https://github.com/SciTools/iris/pulls
.. _pull requests: https://github.com/SciTools/iris/pulls
.. _contributor: https://github.com/SciTools/scitools.org.uk/blob/master/contributors.json
.. _core developers: https://github.com/SciTools/scitools.org.uk/blob/master/contributors.json
.. _iris-test-data: https://github.com/SciTools/iris-test-data
.. _iris-sample-data: https://github.com/SciTools/iris-sample-data
.. _test-iris-imagehash: https://github.com/SciTools/test-iris-imagehash
.. _readthedocs.yml: https://github.com/SciTools/iris/blob/master/requirements/ci/readthedocs.yml
.. _travis-ci: https://travis-ci.org/github/SciTools/iris
.. _.travis.yml: https://github.com/SciTools/iris/blob/master/.travis.yml
.. _.stickler.yml: https://github.com/SciTools/iris/blob/master/.stickler.yml
.. _.flake8.yml: https://github.com/SciTools/iris/blob/master/.flake8
.. _GitHub Help Documentation: https://docs.github.com/en/github
.. _using git: https://docs.github.com/en/github/using-git
.. _generating sss keys for GitHub: https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account
.. _New Issue: https://github.com/scitools/iris/issues/new/choose
.. _matplotlib: https://matplotlib.org/
.. _conda: https://docs.conda.io/en/latest/
.. _sphinx: https://www.sphinx-doc.org/en/master/
.. _napolean: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/sphinxcontrib.napoleon.html
.. _legacy documentation: https://scitools.org.uk/iris/docs/v2.4.0/
.. _cirrus-ci: https://cirrus-ci.com/github/SciTools/iris
