.. _SciTools: https://github.com/SciTools
.. _Iris: https://github.com/SciTools/iris
.. _Iris GitHub: https://github.com/SciTools/iris
.. _iris mailing list: https://groups.google.com/forum/#!forum/scitools-iris
.. _issue: https://github.com/SciTools/iris/issues
.. _issues: https://github.com/SciTools/iris/issues
.. _pull request: https://github.com/SciTools/iris/pulls
.. _pull requests: https://github.com/SciTools/iris/pulls
.. _core developers: https://github.com/SciTools/scitools.org.uk/blob/master/contributors.json
.. _travis-ci: https://travis-ci.org/github/SciTools/iris

.. _GitHub Help Documentation: https://docs.github.com/en/github
.. _using git: https://docs.github.com/en/github/using-git
.. _generating sss keys for GitHub: https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

.. _Iris GitHub: https://github.com/SciTools/iris
.. _Iris: https://github.com/SciTools/iris
.. _issue: https://github.com/SciTools/iris/issues
.. _issues: https://github.com/SciTools/iris/issues
.. _pull request: https://github.com/SciTools/iris/pulls
.. _pull requests: https://github.com/SciTools/iris/pulls
.. _contributor: https://github.com/SciTools/scitools.org.uk/blob/master/contributors.json
.. _SciTools ogranisation: https://scitools.org.uk/

.. _New Issue: https://github.com/scitools/iris/issues/new/choose

.. _matplotlib: https://matplotlib.org/
