version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_checkout:
      # The SciTools/iris repository is shallow i.e., has a .git/shallow,
      # therefore complete the repository with a full history in order
      # to allow setuptools-scm to correctly auto-discover the version.
      - git fetch --unshallow
      - git fetch --all
    # Need to stash the local changes that Read the Docs makes so that
    #  setuptools_scm can generate the correct Iris version.
    pre_install:
      - git stash
    post_install:
      - git stash pop

conda:
  environment: requirements/readthedocs.yml

sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
