version: 2

build:
    image: latest

conda:
    environment: requirements/ci/readthedocs.yml

sphinx:
    configuration: docs/iris/src/conf.py
    fail_on_warning: false

python:
    install: 
        - method: setuptools
          path: .

formats:
    - htmlzip
    - pdf
