linters:
    flake8:
        python: 3
        config: ./.flake8

files:
    ignore:
        - 'lib/iris/fileformats/um_cf_map.py'
        - 'lib/iris/fileformats/_ff_cross_references.py'
        - 'lib/iris/std_names.py'
        - 'lib/iris/fileformats/*.py'
        - 'lib/iris/analysis/*.py'
        - 'lib/iris/palette.py'
        - 'lib/iris/plot.py'
        - 'lib/iris/tests/*.py'
        - 'lib/iris/tests/experimental/*.py'
        - 'lib/iris/tests/experimental/regrid/*.py'
        - 'lib/iris/tests/integration/*.py'
        - 'lib/iris/tests/integration/format_interop/*.py'
        - 'lib/iris/tests/integration/plot/*.py'
        - 'lib/iris/tests/runner/*.py'
        - 'lib/iris/tests/stock/*.py'
        - 'lib/iris/tests/unit/*.py'
        - 'lib/iris/tests/unit/analysis/*.py'
        - 'lib/iris/tests/unit/analysis/cartography/*.py'
        - 'lib/iris/tests/unit/analysis/interpolation/*.py'
        - 'lib/iris/tests/unit/analysis/maths/*.py'
        - 'lib/iris/tests/unit/analysis/regrid/*.py'
        - 'lib/iris/tests/unit/analysis/scipy_interpolate/*.py'
        - 'lib/iris/tests/unit/analysis/trajectory/*.py'
        - 'lib/iris/tests/unit/concatenate/*.py'
        - 'lib/irsi/tests/unit/coord_systems/*.py'
        - 'lib/iris/tests/unit/coords/*.py'
        - 'lib/iris/tests/unit/cube/*.py'
        - 'lib/iris/tests/unit/data_manager/*.py'
        - 'lib/iris/tests/unit/experimental/representation/*.py'
        - 'lib/iris/tests/unit/experimental/stratify/*.py'
        - 'lib/iris/tests/unit/fileformats/cf/*.py'
        - 'lib/iris/tests/unit/fileformats/ff/*.py'
        - 'lib/iris/tests/unit/fileformats/name_loaders/*.py'
        - 'lib/iris/tests/unit/fileformats/netcdf/*.py'
        - 'lib/iris/tests/unit/fileformats/pp/*.py'
        - 'lib/iris/tests/unit/fileformats/pp_load_rules/*.py'
        - 'lib/iris/tests/unit/fileformats/pyke_rules/compiled_krb/fc_rules_cf_fc/*.py'
        - 'lib/iris/tests/unit/fileformats/um/fast_load_structured_fields/*.py'
        - 'lib/iris/tests/unit/fileformats/um/optimal_array_structuring/*.py'
        - 'lib/iris/tests/unit/plot/*.py'
        - 'lib/iris/tests/unit/time/*.py'
        - 'lib/iris/tests/unit/util/*.py'
