#
# This is a *fake / non-functional* travis configuration file.
#
# Its sole purpose at the moment is to record which Cartopy version was
# used for testing.
#
# Cartopy version: 908739960b7a15048ec4ae989416fe05a523dede
#
