#
# Based on pelson's travis work for cartopy.
#
# Please update the cartopy, test data, and sample data git references below if appropriate.
#
# Note: Contrary to the travis documentation,
# http://about.travis-ci.org/docs/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
# we will use the system python because it takes too long to install scipy from source.
#


language: python
python:
  - 2.7

git:
  depth: 0

install:

  - deactivate
  - wget http://repo.continuum.io/miniconda/Miniconda-3.0.5-Linux-x86_64.sh
  - chmod +x Miniconda-3.0.5-Linux-x86_64.sh
  - ./Miniconda-3.0.5-Linux-x86_64.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda create -n test_env numpy=1.7.1

script:
  - python -c "import numpy as np; print np.__version__"
