name: "tox cache"
description: "cache the tox test environments"

inputs:
  cache_build:
    description: "tox cache build number"
    required: false
    default: "0"
  env_name:
    description: "environment name"
    required: true
  lock_file:
    description: "conda-lock environment requirements filename"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.tox
        key: ${{ runner.os }}-tox-${{ inputs.env_name }}-s${{ matrix.session }}-py${{ matrix.python-version }}-b${{ inputs.cache_build }}-${{ hashFiles(inputs.lock_file) }}
