name: "iris-data-cache"
description: "create and cache the iris test data"

inputs:
  cache_build:
    description: "data cache build number"
    required: false
    default: "0"
  env_name:
    description: "environment name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Iris test data version
      shell: bash
      run: echo "IRIS_TEST_DATA_VERSION=$(grep '^TEST_DATA_VERSION = ' lib/iris/tests/__init__.py)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      id: data-cache
      with:
        path: ~/iris-test-data
        key: ${{ runner.os }}-iris-test-data-${{ inputs.env_name }}-v${IRIS_TEST_DATA_VERSION}-b${{ inputs.cache_build }}

    - if: steps.data-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget --quiet https://github.com/SciTools/iris-test-data/archive/v${IRIS_TEST_DATA_VERSION}.zip -O iris-test-data.zip
        unzip -q iris-test-data.zip
        mv iris-test-data-${IRIS_TEST_DATA_VERSION} ${HOME}/iris-test-data
