
// This file was automatically generated by gen_gallery.py & should not be modified directly.

images = new Array();

images[0] = ['plot_directive/example_code/graphics/thumbnails/COP_1d_plot.png', '_images/COP_1d_plot.png', 'examples/graphics/COP_1d_plot.html#COP-1d-plot', 'Iris examples.'];
images[1] = ['plot_directive/example_code/graphics/thumbnails/COP_maps.png', '_images/COP_maps.png', 'examples/graphics/COP_maps.html#COP-maps', 'Iris examples.'];
images[2] = ['plot_directive/example_code/graphics/thumbnails/TEC.png', '_images/TEC.png', 'examples/graphics/TEC.html#TEC', 'Iris examples.'];
images[3] = ['plot_directive/example_code/graphics/thumbnails/cross_section_00.png', '_images/cross_section_00.png', 'examples/graphics/cross_section.html#cross-section-00', 'Iris examples.'];
images[4] = ['plot_directive/example_code/graphics/thumbnails/cross_section_01.png', '_images/cross_section_01.png', 'examples/graphics/cross_section.html#cross-section-01', 'Iris examples.'];
images[5] = ['plot_directive/example_code/graphics/thumbnails/custom_file_loading.png', '_images/custom_file_loading.png', 'examples/graphics/custom_file_loading.html#custom-file-loading', 'Iris examples.'];
images[6] = ['plot_directive/example_code/graphics/thumbnails/deriving_phenomena.png', '_images/deriving_phenomena.png', 'examples/graphics/deriving_phenomena.html#deriving-phenomena', 'Iris examples.'];
images[7] = ['plot_directive/example_code/graphics/thumbnails/global_map.png', '_images/global_map.png', 'examples/graphics/global_map.html#global-map', 'Iris examples.'];
images[8] = ['plot_directive/example_code/graphics/thumbnails/hovmoller.png', '_images/hovmoller.png', 'examples/graphics/hovmoller.html#hovmoller', 'Iris examples.'];
images[9] = ['plot_directive/example_code/graphics/thumbnails/lagged_ensemble_00.png', '_images/lagged_ensemble_00.png', 'examples/graphics/lagged_ensemble.html#lagged-ensemble-00', 'Iris examples.'];
images[10] = ['plot_directive/example_code/graphics/thumbnails/lagged_ensemble_01.png', '_images/lagged_ensemble_01.png', 'examples/graphics/lagged_ensemble.html#lagged-ensemble-01', 'Iris examples.'];
images[11] = ['plot_directive/example_code/graphics/thumbnails/lineplot_with_legend.png', '_images/lineplot_with_legend.png', 'examples/graphics/lineplot_with_legend.html#lineplot-with-legend', 'Iris examples.'];
images[12] = ['plot_directive/example_code/graphics/thumbnails/rotated_pole_mapping_00.png', '_images/rotated_pole_mapping_00.png', 'examples/graphics/rotated_pole_mapping.html#rotated-pole-mapping-00', 'Iris examples.'];
images[13] = ['plot_directive/example_code/graphics/thumbnails/rotated_pole_mapping_01.png', '_images/rotated_pole_mapping_01.png', 'examples/graphics/rotated_pole_mapping.html#rotated-pole-mapping-01', 'Iris examples.'];
images[14] = ['plot_directive/example_code/graphics/thumbnails/rotated_pole_mapping_02.png', '_images/rotated_pole_mapping_02.png', 'examples/graphics/rotated_pole_mapping.html#rotated-pole-mapping-02', 'Iris examples.'];
images[15] = ['plot_directive/example_code/graphics/thumbnails/rotated_pole_mapping_03.png', '_images/rotated_pole_mapping_03.png', 'examples/graphics/rotated_pole_mapping.html#rotated-pole-mapping-03', 'Iris examples.'];

