# This is a basic workflow to help you get started with Actions

name: benchmark-check

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch the PR base branch too
        run: |
          echo "PR_BASE_SHA=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          git fetch --depth=1 origin ${{ env.PR_BASE_SHA }}

      - name: Install Nox
        run: |
          pip install nox

      - name: Run CI benchmarks
        run: |
          nox --session="benchmarks(ci compare)" > benchmarks/.asv/ci_compare.txt

      - name: Archive asv results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: asv-report
          path: |
            benchmarks/.asv/results
            benchmarks/.asv/compare.txt