# This is a basic workflow to help you get started with Actions

name: benchmark-check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup asv
        run: |
          pip install asv
          cd benchmarks
          asv machine --yes --machine gh-actions

      - name: Run benchmarks on source and target
        run: |
          cd benchmarks
          # run asv benchmarks on the target
          git fetch ${{ github.base_ref }}
          asv run ${{ github.base_ref }}  -s 1 -b import_iris
          # run asv on the head of this PR
          asv run ${{ github.head_ref }}  -s 1 -b import_iris
          asv publish

      - name: Archive asv results
        uses: actions/upload-artifact@v2
        with:
          name: asv-report
          path: |
            benchmarks/.asv/html
            benchmarks/.asv/results