# This is a basic workflow to help you get started with Actions

name: benchmark-check

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      BASE: ${{ github.event.pull_request.base.ref }}
      HEAD: ${{ github.sha }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup asv
        run: |
          pip install asv
          cd benchmarks
          asv machine --yes

      - name: Run benchmarks on source and target
        run: |
          cd benchmarks
          asv continuous origin/$BASE $HEAD

      - name: Write a compare file to the output folder
        if: ${{ always() }}
        run: |
          cd benchmarks
          asv compare -s origin/$BASE $HEAD > .asv/compare.txt

      - name: Archive asv results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: asv-report
          path: |
            benchmarks/.asv/results
            benchmarks/.asv/compare.txt