# Reference:
#   - https://github.com/actions/checkout
#   - https://github.com/citation-file-format/cffconvert-github-action

name: ci-citation

on:
  pull_request:
    paths:
      - "CITATION.cff"

  push:
    paths:
      - "CITATION.cff"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "check CITATION.cff"
        uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084
        with:
          args: "--validate"
