# Reference
#    - https://github.com/actions/checkout
#    - https://github.com/SciTools/workflows

name: ci-manifest

on:
  pull_request:
    branches:
      - "*"

  push:
    branches-ignore:
      - "auto-update-lockfiles"
      - "pre-commit-ci-update-config"
      - "dependabot/*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  manifest:
    name: "check-manifest"
    uses: scitools/workflows/.github/workflows/ci-manifest.yml@28aea7a3a1eb58e1bbf9b1d9c8cb2de07892b67e
