# Checks if a PR makes any changes that ought to be shared via templating.
# See the called workflow in the scitools/workflows repo for more details.

name: ci-template-check

on:
  pull_request_target:  # zizmor: ignore[dangerous-triggers]
    branches:
      - main

permissions: {}

jobs:
  prompt-share:
    uses: scitools/workflows/.github/workflows/ci-template-check.yml@1f2141422a63321a32575ddd186e53acff12550c
    secrets:
      AUTH_APP_ID: ${{ secrets.AUTH_APP_ID }}
      AUTH_APP_PRIVATE_KEY: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
    with:
      pr_number: ${{ github.event.pull_request.number }}
