# reference:
#   - https://github.com/actions/cache
#   - https://github.com/actions/checkout
#   - https://github.com/marketplace/actions/setup-miniconda

name: ci-tests 

on:
  push:
    branches:
      - "*" 

  pull_request:
    branches:
      - "*" 

jobs:
  tests:
    name: ${{ matrix.os }} ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
        include:
          - os: ubuntu-latest
            lock-file: requirements/ci/nox.lock/py38-linux-64.lock

    env:
      IRIS_TEST_DATA_VERSION: "2.5"
      ENV_NAME: "iris-ci"
      # https://github.com/numpy/numpy/pull/19478
      NPY_DISABLE_CPU_FEATURES: "AVX512F,AVX512CD,AVX512VL,AVX512BW,AVX512DQ,AVX512_SKX"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Environment configure"
        env:
          # Maximum cache period (in weeks) before forcing a cache refresh.
          CACHE_WEEKS: 2
        run: |
          echo "CACHE_PERIOD=$(date +%Y).$(expr $(date +%U) / ${CACHE_WEEKS})" >> ${GITHUB_ENV}

      - name: "Data cache"
        uses: actions/cache@v2
        id: data-cache
        env:
          # Increment the build number to force a cache refresh.
          CACHE_BUILD: 0
        with:
          path: ~/iris-test-data
          key: ${{ runner.os }}-iris-test-data-v${{ env.IRIS_TEST_DATA_VERSION }}-b${{ env.CACHE_BUILD }}

      - name: "Data cache populate"
        if: steps.data-cache.outputs.cache-hit != 'true'
        run: |
          wget --quiet https://github.com/SciTools/iris-test-data/archive/v${{ env.IRIS_TEST_DATA_VERSION }}.zip -O iris-test-data.zip
          unzip -q iris-test-data.zip
          mv iris-test-data-${{ env.IRIS_TEST_DATA_VERSION }} ${HOME}/iris-test-data

      - name: "Conda package cache"
        uses: actions/cache@v2
        env:
          # Increment the build number to force a cache refresh.
          CACHE_BUILD: 0
          LOCK_FILE: ${{ matrix.lock-file }}
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-pkgs-py${{ matrix.python-version }}-b${{ env.CACHE_BUILD }}-${{ hashFiles(env.LOCK_FILE) }}

      - name: "Conda install"
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: ${{ env.ENV_NAME }}
          auto-update-conda: false
          use-only-tar-bz2: true

      - name: "Conda environment cache"
        uses: actions/cache@v2
        id: conda-env-cache
        env:
          # Increment the build number to force a cache refresh.
          CACHE_BUILD: 0
          LOCK_FILE: ${{ matrix.lock-file }}
        with:
          path: ${{ env.CONDA }}/envs/${{ env.ENV_NAME }}
          key: ${{ runner.os }}-conda-env-${{ env.ENV_NAME }}-py${{ matrix.python-version }}-b${{ env.CACHE_BUILD }}-${{ hashFiles(env.LOCK_FILE) }}

      - name: "Conda environment update"
        if: steps.conda-env-cache.outputs.cache-hit != 'true'
        run: |
          mamba install --name ${{ env.ENV_NAME }} --file ${{ matrix.lock-file }}

      - name: "Conda info"
        run: |
          conda info
          conda list

      - name: "Cartopy cache"
        uses: actions/cache@v2
        id: cartopy-cache
        env:
          # Increment the build number to force a cache refresh.
          CACHE_BUILD: 0
        with:
          path: ~/.local/share/cartopy
          key: ${{ runner.os }}-cartopy-p${{ env.CACHE_PERIOD }}-b${{ env.CACHE_BUILD }}

      - name: "Cartopy cache populate"
        if: steps.cartopy-cache.outputs.cache-hit != 'true'
        env:
          CARTOPY_SHARE_DIR: ~/.local/share/cartopy
          CARTOPY_FEATURE: https://raw.githubusercontent.com/SciTools/cartopy/v0.20.0/tools/cartopy_feature_download.py
        run: |
          wget --quiet ${CARTOPY_FEATURE}
          mkdir -p ${CARTOPY_SHARE_DIR}
          # Requires a pre-installed version of cartopy within the environment.
          python cartopy_feature_download.py physical --output ${CARTOPY_SHARE_DIR} --no-warn

      - name: "Iris install"
        run: |
          python -m pip install --no-deps -e .

      - name: "Iris configure"
        env:
          SITE_CFG: lib/iris/etc/site.cfg
        run: |
          echo "[Resources]" >> ${SITE_CFG}
          echo "test_data_dir = ${HOME}/iris-test-data/test_data" >> ${SITE_CFG}
          echo "doc_dir = ${GITHUB_WORKSPACE}/docs" >> ${SITE_CFG}
          cat ${SITE_CFG}

      - name: "Iris import"
        run: |
          python -c "import iris; print(f'Iris v{iris.__version__}')"

      - name: "Iris test"
        run: |
          python -m iris.tests.runner --default-tests --system-tests
