# Reference
#   - https://github.com/actions/labeler

name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  runs-on: ubuntu-latest

  steps:
    - name: "Generate token"
      uses: tibdex/github-app-token@v2
      id: generate-token
      with:
        app_id: ${{ secrets.AUTH_APP_ID }}
        private_key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}

    - uses: actions/labeler@v5
      with:
        repo-token: ${{ steps.generate-token.outputs.token }}