# Uses Github API to get a list of issues that have votes on and then
# update a gist with the results in json

name: Refresh Votable Issues
on:
  workflow_dispatch:
    branches: [ votable_issues ]
jobs:
  votable_main:
    runs-on: ubuntu-latest
    steps:
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout iris
        uses: actions/checkout@v2
        with:
          repository: tkknight/iris
          ref: votable_issues
          path: iris

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install PyGithub
#    - name: Run the python
#      run: |
#        python ${{ github.action_path }}/iris/docs/src/query_gh_votable_issues.py ${{ secrets.gh_token }}

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install PyGithub
#    - name: Run the python
#      run: |
#        python ${{ github.action_path }}/iris/docs/src/query_gh_votable_issues.py ${{ secrets.gh_token }}



#      - uses: actions/script@v4
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            echo "hello world"
#            python iris/docs/src/query_gh_votable_issues.py ${{ secrets.GITHUB_TOKEN }}
#            cat votable-issues.json
#
      - name: echo test
        run: echo "Hello World!";ls -al $GITHUB_WORKSPACE/iris/docs/src
