# Uses Github API to get a list of issues that have votes on and then
# update a gist with the results in json

name: Refresh Votable Issues
on:
  workflow_dispatch:
    branches: [ votable_issues ]
jobs:
  votable_main:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "ls command";ls -al
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout iris
        uses: actions/checkout@v2
        with:
          repository: tkknight/iris
          path: iris

#      - uses: actions/script@v4
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            echo "hello world"
#            docs/src/query_gh_votable_issues.py ${{ secrets.GITHUB_TOKEN }}
#            cat votable-issues.json

      - name: echo test
        run: echo "Hello World!"
