# This is a basic workflow to help you get started with Actions

name: Refresh Lockfiles

# Controls when the action will run. 
on:
#   schedule:
#     - cron: 1 0 * * 6

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches: [ ci-lock ]

jobs:
  gen_lockfiles:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python: ['36', '37', '38']
    
    steps:
      - uses: actions/checkout@v2
      - name: install conda-lock
        run: |
          source $CONDA/bin/activate base
          conda install -y -c conda-forge conda-lock
      - name: generate lockfile
        run: |
          $CONDA/bin/conda-lock lock -p linux-64 -f requirements/ci/py${{matrix.python}}.yml
          mv conda-linux-64.lock py${{matrix.python}}-linux-64.lock
      - name: output lockfile
        uses: actions/upload-artifact@v2
        with:
          path: py${{matrix.python}}-linux-64.lock
    
  create_pr:
    runs-on: ubuntu-latest
    needs: gen_lockfiles
    
    steps:
      - uses: actions/checkout@v2
      - name: get artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
          
      - name: Update lock files in repo
        run: | 
          cp artifacts/artifact/*.lock requirements/ci/nox.lock
          rm -r artifacts
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@052fc72b4198ba9fbc81b818c6e1859f747d49a8
        with:
          commit-message: Updated environment lockfiles
          delete-branch: true
          branch: lockfiles-
          branch-suffix: timestamp
          title: Update CI environment lockfiles
          body: |
            Lockfiles updated to the latest resolvable environment.
