# See https://github.com/actions/stale

name: Stale issues and pull-requests

on:
  schedule:
    # Run once a day
    # N.B. "should" be quoted, according to
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: "0 0 * * *"

jobs:
  stale:
    if: "github.repository == 'SciTools/iris'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Idle number of days before marking issues/prs stale.
          days-before-stale: 500

          # Idle number of days before closing stale issues/prs.
          days-before-close: 28

          # Comment on the staled issues.
          stale-issue-message: |
            It has been 500 days since last activity on this issue, so it has been given the https://github.com/SciTools/iris/labels/needs-checkin label. This reminder prompts us to identify issues which:
            
            1. Have been resolved since their last update.
            2. Are no longer relevant.
            3. Are still outstanding and should be assigned resource.
            4. Are still outstanding but which there is not enough resource for - our backlog is often larger than available resource; the 500-day inactivity _may_ be a sign of lower priority.
            
            If this issue is still important to you, then please comment on this issue. The https://github.com/SciTools/iris/labels/needs-checkin label will be automatically removed.
            
            If there is no activity on this issue for 28 days: it will be closed and given the https://github.com/SciTools/iris/labels/not-resourced label.

          # Comment on the staled prs.
          stale-pr-message: |
            It has been 500 days since last activity on this PR, so it has been given the https://github.com/SciTools/iris/labels/needs-checkin label. This reminder prompts us to identify PRs which:
            
            1. Are for a problem that is now fixed.
            2. Are no longer relevant.
            3. Are still outstanding and should be assigned resource.
            4. Are still outstanding but which there is not enough resource for - our backlog is often larger than available resource; the 500-day inactivity _may_ be a sign of lower priority.
            
            If this PR is still important to you, then please comment on this PR. The https://github.com/SciTools/iris/labels/needs-checkin label will be automatically removed.
            
            If there is no activity on this PR for 28 days: it will be closed and given the https://github.com/SciTools/iris/labels/not-resourced label.

          # Comment on the staled issues while closed.
          close-issue-message: |
            This issue has been automatically closed due to inactivity, with the https://github.com/SciTools/iris/labels/not-resourced label.
            
            If you still want this issue to get attention, then please either:
            
            - Re-open this issue, if you have sufficient permissions, or ...
            - Add a comment pinging `@SciTools/iris-devs` who will re-open on your behalf.

          # Comment on the staled prs while closed.
          close-pr-message: |
            This PR has been automatically closed due to inactivity, with the https://github.com/SciTools/iris/labels/not-resourced label.
            
            If you still want this PR to get attention, then please either:
            
            - Re-open this PR, if you have sufficient permissions, or ...
            - Add a comment pinging `@SciTools/iris-devs` who will re-open on your behalf.

          # Label to apply on staled issues.
          stale-issue-label: needs-checkin

          # Label to apply on staled prs.
          stale-pr-label: needs-checkin

          # Label to apply on closed issues.
          close-issue-label: not-resourced

          # Label to apply on closed prs.
          close-pr-label: not-resourced

          # Labels on issues exempted from stale.
          exempt-issue-labels:
            "Status: Blocked,Status: Decision Required,Peloton 🚴‍♂️,Good First Issue, Dragon 🐉, Dragon Sub-Task 🦎, Release: Major"

          # Labels on prs exempted from stale.
          exempt-pr-labels:
            "Status: Blocked,Status: Decision Required,Peloton 🚴‍♂️,Good First Issue, Dragon 🐉, Dragon Sub-Task 🦎, Release: Major"

          # Max number of operations per run.
          operations-per-run: 300

          # Remove stale label from issues/prs on updates/comments.
          remove-stale-when-updated: true

          # Order to get issues/PRs.
          ascending: true

          # Exempt all issues/prs with milestones from stale.
          exempt-all-milestones: true
